### ISSUE TITLE
Inserir react no projeto

### ISSUE THREAD

**Issue by lucasmaiaesilva** [jjaderg/dialetus#2]
Instalar o react e rodá-lo ao boilerplate do projeto via browserify, webpack, bower, gulp ou qualquer outra maneira considerada viável.

**Comment by jjaderg** [comment]
Acho uma boa usar o Webpack pra o react e o Gulp pra a stack do Frontend , e vocês? @lucasmaiaesilva  & @afonsopacifer

**Comment by afonsopacifer** [comment]
Acho irado:)
