### ISSUE TITLE
 [Layout] - Discussão sobre a interface

### ISSUE THREAD

**Issue by jjaderg** [jjaderg/dialetus#6]
Fiz esses mockups de como imaginei o layout do projeto.:pencil2:

![dialetusmockup](https://cloud.githubusercontent.com/assets/15023006/14944381/9e6d7060-0fc7-11e6-975d-0d729b5086f3.png)

Veja que no card:
   + Círculo  (imagem da bandeira do estado)
   + Palavra (É nada mais que a expressão)
   + Região  (Qual região/cidade/whatever do estado em questão essa palavra é falada )
   + Parágrafo (Significado e exemplos do uso dessa expressão)

![dialetusmockup-2](https://cloud.githubusercontent.com/assets/15023006/14944404/82c576ea-0fc8-11e6-9fd5-32ed38116465.png)

Agora nesse outro mockup, pensei em fazer como os cards do google+, que quando é clicado, ele explodi suavemente dando um overlay branco opaco em todo o resto! :smile:

O que vocês acham e podem contribuir @lucasmaiaesilva  @afonsopacifer

**Comment by afonsopacifer** [comment]
Posso fazer algo no photoshop, vou tentar fazer algo e post aqui hoje na madruga ou amanhã :)

**Comment by jjaderg** [comment]
Madrugada tem novidade então, rsrs.

**Comment by mvfsilva** [comment]
E ai @jjaderg quero mandar bala nesse projeto, qual vai ser a stack?

**Comment by jjaderg** [comment]
vue + postcss + stylus @mvfsilva
